[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm install && pnpm run build && node dist/main.js"
healthcheckPath = "/wilayas"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10